---
- calls:
    - "-a"
    - "--action"
  help: What action to take
  dest: action
  env: PLUGIN_ACTION

- calls:
    - "-v"
    - "--vault"
  action: store
  dest: vault_address
  help: Address for Vault instance
  env: PLUGIN_VAULT_ADDRESS

- calls:
    - "-s"
    - "--secret"
  action: store
  dest: secret
  help: name of the secret where vault root key and unseal keys will be writen to,
    defaults to `vault`, or where the tls certificate will be writen to, defaults
    to `vault-tls`
  env: PLUGIN_SECRET

- calls:
    - "-c"
    - "--config"
  action: store
  dest: config
  help: Extra config path, currently used in vault setup
  env: PLUGIN_CONFIG_PATH

- calls:
    - "-t"
    - "--token"
  action: store
  dest: vault_token
  help: Address for Vault instance
  env: PLUGIN_VAULT_TOKEN

- calls:
    - "-k"
    - "--kubernetes_address"
  action: store
  dest: k_address
  help: Address for Vault instance
  env: PLUGIN_KUBERNETES_ADDRESS

- calls:
    - "-d"
    - "--details"
  action: store
  dest: details
  help: Path to the details file of this installation
  env: PLUGIN_DETAILS_FILE

- calls:
    - "--kubernetes_ca"
  action: store
  dest: k_ca
  help: Address for Vault instance
  env: PLUGIN_KUBERNETES_CA

- calls:
    - "--kubernetes_token"
  action: store
  dest: k_token
  help: Address for Vault instance
  env: PLUGIN_KUBERNETES_TOKEN_PATH

- calls:
  - "--vault_ca"
  action: store
  dest: v_ca
  help: Certificate authority path for Vault
  env: PLUGIN_VAULT_CA

- calls:
  - "--sign_ca"
  action: store
  dest: sign_ca
  help: Certificate authority key path to sign the certificate
  env: PLUGIN_SIGN_CA

- calls:
  - "--sign_ca_key"
  action: store
  dest: sign_ca_key
  help: Certificate authority path to sign the certificate
  env: PLUGIN_SIGN_CA_KEY

- calls:
    - "--common_name"
  action: store
  dest: common_name
  help: Common name to use for vault cert
  env: PLUGIN_COMMON_NAME

- calls:
    - "-b"
    - "--base_path"
  action: store
  dest: base_path
  help: Base path to the required resources
  env: PLUGIN_BASE_PATH